name: Compliance check with CloudFormation Guard
on:
  push: {branches: dev}

defaults:
  run:
      shell: bash
jobs:
  check-cfn-templates:
    name: Check AWS CloudFormation templates
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Install CloudFormation Guard
        env: 
          CFN_GUARD_VERSION: 1.0.0
        run: |
          wget https://github.com/aws-cloudformation/cloudformation-guard/releases/download/${CFN_GUARD_VERSION}/cfn-guard-linux-${CFN_GUARD_VERSION}.tar.gz
          tar -xvf cfn-guard-linux-${CFN_GUARD_VERSION}.tar.gz
      - name: Generate the ruleset and Check the compliance with CFT
        run: |
          ./cfn-guard-linux/cfn-guard rulegen modules/quickstart/nap-autoscale-ubuntu-dev.yaml > modules/quickstart/nap-autoscale.ruleset 
          echo "Generated Ruleset for CFT"
          cat modules/quickstart/nap-autoscale.ruleset
          ./cfn-guard-linux/cfn-guard check -t modules/quickstart/nap-autoscale-ubuntu-dev.yaml -r modules/quickstart/nap-autoscale.ruleset